### ISSUE TITLE
一打开就crash； CalcMac.init(externalPath);这个初始化

### ISSUE THREAD

**Issue by wwprootor** [sheng895/androidtts#3]
CalcMac.init(externalPath);

**Comment by sheng895** [comment]
请按步骤 编译C++ ,Android Studio 终端， cd  TTSAndroid\voicetts\src\main\jni  执行  ndk-build编译能过，生成对应的so文件，如果不编译，没有so文件就会报错，另外Android SDK build-tools 的版本为33.0.1。
